{{- define "ports.list" -}}
{{- if .Values.ports }}
{{- range .Values.ports }}{{(print .exposedPort ":" .targetIp ":" .targetPort ":" .protocol ) }},{{- end }}
{{- end }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: tunnel-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunnel-ingress
  template:
    metadata:
      labels:
        app: tunnel-ingress
    spec:
      volumes:
        - name: ssh-key
          secret:
            secretName: ssh-key
            defaultMode: 0400
        - name: run-dir
          emptyDir: {}
      containers:
        - name: tunnel
          image: dajudge/tunnel-ingress:{{ .Values.tag }}
          volumeMounts:
            - name: ssh-key
              mountPath: /ssh-key/
              readOnly: true
            - name: run-dir
              mountPath: /var/run/tunnel-ingress/
          env:
            - name: INTERNAL_PRIVATE_IP
              value: {{ .Values.internalPrivateIp }}
            - name: EXTERNAL_PRIVATE_IP
              value: {{ .Values.externalPrivateIp }}
            - name: PORTS
              value: '{{- include "ports.list" . | trimSuffix "," }}'
            - name: HOST
              value: {{ .Values.host }}
            - name: PING_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pingSecret.name }}
                  key: {{ .Values.pingSecret.key }}
          securityContext:
            privileged: true
