internalPrivateIp: 10.42.0.1
externalPrivateIp: 10.42.0.2
host: ip or hostname of the external host
sshKeySecret: ssh-key
pingSecret:
  name: ping-secret
  key: url
tag: 0.0.6
ports:
  - exposedPort: 80
    targetIp: someIp
    targetPort: 30080
  - exposedPort: 443
    targetIp: someIp
    targetPort: 30443
